### ISSUE TITLE
Class McdsDataset: Returns labels with the shape of  tensor([3.]) and raises ValueError

### ISSUE THREAD

**Issue by jfltzngr** [phiyodr/bridge-inspection-toolkit#2]
## Environment info
- `bikit` version: 0.0.11
- Platform: Windows 10
- Used Versions:  Python 3.9.6, Pytorch 1.9.0, Pandas 1.3.3, Numpy 1.21.2

## Information
Class McdsDataset from bikit.datasets.mcds module raises follwoing error:
``ValueError: Target size (torch.Size([32, 1])) must be the same as input size (torch.Size([32, 10]))``
The Label-file (`mcds.csv`) looks like this: 

- Columns: img_name,img_path,target_label,target,split_type
- Exampole-data: WA-9217C_8.JPG,mcds/Corrosion/no rust staining/WA-9217C_8.JPG,Corrosion_NoRustStaining,0,test
- So the label for this image would be: `tensor([0.])`

-> `McdsDataset.__getitem__` only transforms the value in the column `target`, which is an integer (0-9) to a Torch-Float-Tensor.  So no One-Hot-Encoding is performed.  

## To reproduce
`from bikit.datasets.mcds import McdsDataset`
`img, label = McdsDataset(split_type="trainval", transform=train_transforms)`
`print(label)`

## Expected behavior
Returning torch.Tensor with shape of: `torch.Size([32, 10])`.
In the example: `tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])`

**Comment by phiyodr** [comment]
Please use the current bikit version, which is `0.1.2`.

**Comment by jfltzngr** [comment]
Thanks @phiyodr!
